name: Django CI/CD

# ワークフローを実行するタイミングを設定
on:
    push:
        branches:
            - deploy # deployブランチにpushされたとき

jobs:
    deploy:
        runs-on: ubuntu-latest # GitHub Actionsでが使用するosを指定

        steps:
            # 1. コードのチェックアウト
            - name: Checkout code
              uses: actions/checkout@v3
            
            # 2. Pythonのセットアップ
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.8'
            
            # 3. 依存関係のインストール
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # 4. データベースのマイグレーション
            - name: Run migrations
              run: |
                python manage.py migrate

            # 2. Heroku CLIのインストール
            - name: Install Heroku CLI
              run: |
                curl https://cli-assets.heroku.com/install.sh | sh
                echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

            # 3. Herokuにデプロイ
            - name: Deploy to Heroku
              run: |
                heroku git:remote -a helloworld-tamk
                git push heroku deploy:main
