name: Django CI/CD

# ワークフローを実行するタイミングを設定
on:
    push:
        branches:
            - deploy
            - feature/* # deployブランチにpushされたとき

jobs:
    deploy:
        runs-on: ubuntu-latest # GitHub Actionsでが使用するosを指定

        steps:
            # 1. コードのチェックアウト
            - name: Checkout code
              uses: actions/checkout@v3
            
            # 2. Pythonのセットアップ
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            # 3. 依存関係のインストール
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt


            # 2. Heroku CLIのインストールとログイン
            - name: Install Heroku CLI
              run: |
                curl https://cli-assets.heroku.com/install.sh | sh
                echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:login --with-token
            
            # Herokuリモートを設定
            - name: Add Heroku remote
              run: |
                heroku git:remote -a helloworld-tamk
            
            # 環境変数をherokuに登録
            - name: Set environment variables on Heroku
              run: |
                heroku config:set SECRET_KEY=${{ secrets.SECRET_KEY }} --app helloworld-tamk
                heroku config:set ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} --app helloworld-tamk
            
            # 4. データベースのマイグレーション
            - name: Run migrations
              run: |
                python manage.py migrate
            
            # 3. Herokuにデプロイ
            - name: Deploy to Heroku
              run: |
                git push heroku deploy:main
